//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurigma.GraphicsMill.AjaxControls.VectorObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aurigma.GraphicsMill.AjaxControls.VectorObjects.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; resource not found..
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not deserialize canvas..
        /// </summary>
        internal static string CanNotDeserializeCanvas {
            get {
                return ResourceManager.GetString("CanNotDeserializeCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not download image..
        /// </summary>
        internal static string CanNotDownloadImage {
            get {
                return ResourceManager.GetString("CanNotDownloadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not draw non-cached image..
        /// </summary>
        internal static string CanNotDrawImageByUrl {
            get {
                return ResourceManager.GetString("CanNotDrawImageByUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not parse SvgVoContent..
        /// </summary>
        internal static string CanNotParseSvgVoContent {
            get {
                return ResourceManager.GetString("CanNotParseSvgVoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not parse SvgVoCurvedText..
        /// </summary>
        internal static string CanNotParseSvgVoCurvedText {
            get {
                return ResourceManager.GetString("CanNotParseSvgVoCurvedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not parse SvgVoDashLine..
        /// </summary>
        internal static string CanNotParseSvgVoDashLine {
            get {
                return ResourceManager.GetString("CanNotParseSvgVoDashLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not parse SvgVoImage..
        /// </summary>
        internal static string CanNotParseSvgVoImage {
            get {
                return ResourceManager.GetString("CanNotParseSvgVoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not parse SvgVoPlaceholder..
        /// </summary>
        internal static string CanNotParseSvgVoPlaceholder {
            get {
                return ResourceManager.GetString("CanNotParseSvgVoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not parse SvgVoSvg..
        /// </summary>
        internal static string CanNotParseSvgVoSvg {
            get {
                return ResourceManager.GetString("CanNotParseSvgVoSvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not parse SvgVoText..
        /// </summary>
        internal static string CanNotParseSvgVoText {
            get {
                return ResourceManager.GetString("CanNotParseSvgVoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not serialize canvas.
        /// </summary>
        internal static string CanNotSerializeCanvas {
            get {
                return ResourceManager.GetString("CanNotSerializeCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get default color for unknown color space..
        /// </summary>
        internal static string ConNotGetDefaultColorForUnknownColorSpace {
            get {
                return ResourceManager.GetString("ConNotGetDefaultColorForUnknownColorSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download images is not allowed. You can allow it in configuration file..
        /// </summary>
        internal static string DownloadDeny {
            get {
                return ResourceManager.GetString("DownloadDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI should be greater than zero (0)..
        /// </summary>
        internal static string DpiOutOfRange {
            get {
                return ResourceManager.GetString("DpiOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file not found..
        /// </summary>
        internal static string ImageFileNotFound {
            get {
                return ResourceManager.GetString("ImageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item already belongs to this collection, or to another collection..
        /// </summary>
        internal static string ItemBelongsCollection {
            get {
                return ResourceManager.GetString("ItemBelongsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer with specified index ({0}) not found..
        /// </summary>
        internal static string LayerOutOfRange {
            get {
                return ResourceManager.GetString("LayerOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;f&quot; is missing..
        /// </summary>
        internal static string MissingFileIdParameter {
            get {
                return ResourceManager.GetString("MissingFileIdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pipeline elements..
        /// </summary>
        internal static string NoPipelineElements {
            get {
                return ResourceManager.GetString("NoPipelineElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection is read only..
        /// </summary>
        internal static string ReadOnlyCollection {
            get {
                return ResourceManager.GetString("ReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured while rendering canvas workspace..
        /// </summary>
        internal static string RenderCanvasWorkspace {
            get {
                return ResourceManager.GetString("RenderCanvasWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ScriptManager control must exist on the current page..
        /// </summary>
        internal static string ScriptManagerControlRequired {
            get {
                return ResourceManager.GetString("ScriptManagerControlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image URL is incorrectly formatted..
        /// </summary>
        internal static string SourceFormat {
            get {
                return ResourceManager.GetString("SourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize canvas state..
        /// </summary>
        internal static string UnableDeserializeCanvas {
            get {
                return ResourceManager.GetString("UnableDeserializeCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize file..
        /// </summary>
        internal static string UnableDeserializeFile {
            get {
                return ResourceManager.GetString("UnableDeserializeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load color profile from file..
        /// </summary>
        internal static string UnableLoadColorProfile {
            get {
                return ResourceManager.GetString("UnableLoadColorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VObject with specified index ({0}) not found..
        /// </summary>
        internal static string VObjectOutOfRange {
            get {
                return ResourceManager.GetString("VObjectOutOfRange", resourceCulture);
            }
        }
    }
}
